/* Copyright 2020 MelGeek <melgeek001365@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_64_ansi(KC_ESC, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_MINS, KC_EQL, KC_BSPC, KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_LBRC, KC_RBRC, KC_BSLS, KC_LCTL, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, KC_ENT, OSM(MOD_LSFT), KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, OSM(MOD_RSFT), KC_UP, KC_DEL, OSL(1), KC_LALT, KC_LGUI, KC_SPC, MO(2), OSL(1), KC_LEFT, KC_DOWN, KC_RGHT),

	[1] = LAYOUT_64_ansi(
      KC_TILD, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12, KC_NO, KC_GRV, KC_NO, KC_UP, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_PSCR, KC_NO, KC_NO, RESET, KC_NO, KC_LEFT, KC_DOWN, KC_RGHT, KC_NO, KC_NO, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_NO, KC_NO, KC_ENT, CL_CTRL, KC_NO, KC_NO, KC_CAPS, KC_NO, KC_NO, KC_NO, KC_BTN2, KC_HOME, KC_END, KC_NO, CL_CAPS, KC_PGUP, KC_NO, MO(3), KC_TRNS, MO(2), KC_NO, KC_TRNS, KC_TRNS, KC_HOME, KC_PGDN, KC_END),

	[2] = LAYOUT_64_ansi(KC_NO, KC_BRID, KC_BRIU, KC_ACL0, KC_ACL1, KC_ACL2, KC_NO, KC_NO, KC_NO, KC_NO, KC_MUTE, KC_VOLD, KC_VOLU, KC_MPLY, KC_NO, KC_NO, KC_MS_U, KC_NO, KC_NO, KC_NO, KC_MINS, KC_7, KC_8, KC_9, KC_0, KC_LBRC, KC_RBRC, KC_BSLS, KC_LCTL, KC_MS_L, KC_MS_D, KC_MS_R, KC_NO, KC_NO, KC_PLUS, KC_4, KC_5, KC_6, KC_EQL, KC_SCLN, KC_ENT, KC_LSFT, KC_BTN1, KC_BTN3, KC_BTN2, KC_NO, KC_NO, KC_COMM, KC_1, KC_2, KC_3, KC_DOT, KC_RSFT, KC_UP, KC_DEL, KC_NO, KC_LALT, KC_TRNS, KC_SPC, KC_NO, KC_NO, KC_LEFT, KC_DOWN, KC_RGHT),

	[3] = LAYOUT_64_ansi(RGB_TOG, RGB_MOD, RGB_RMOD, RGB_HUI, RGB_HUD, RGB_SAI, RGB_SAD, RGB_VAI, RGB_VAD, RGB_SPI, RGB_SPD, KC_NO, KC_NO, KC_NO, KC_NO, RGB_M_P, RGB_M_B, RGB_M_R, RGB_M_SW, RGB_M_SN, RGB_M_K, RGB_M_X, RGB_M_G, RGB_M_T, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO)
};


enum combo_events {
  JK_ESC,
  QUOT,
  DQUOT,
  LRB,
  LRS,
  LRP,
  COMBO_LENGTH
};

uint16_t COMBO_LEN = COMBO_LENGTH; // remove the COMBO_COUNT define and use this instead!

const uint16_t PROGMEM jk_esc[] = {KC_J, KC_K, COMBO_END};

const uint16_t PROGMEM quot[] = {KC_SCLN, KC_BSLS, COMBO_END};

const uint16_t PROGMEM dquot[] = {KC_L, KC_SCLN, KC_BSLS, COMBO_END};

const uint16_t PROGMEM lrb[] = {KC_M, KC_COMM, COMBO_END};

const uint16_t PROGMEM lrs[] = {KC_P, KC_BSPC, COMBO_END};

const uint16_t PROGMEM lrp[] = {KC_C, KC_V, COMBO_END};

combo_t key_combos[] = {
  [JK_ESC] = COMBO_ACTION(jk_esc),
  [QUOT] = COMBO_ACTION(quot),
  [DQUOT] = COMBO_ACTION(dquot),
  [LRB] = COMBO_ACTION(lrb),
  [LRS] = COMBO_ACTION(lrs),
  [LRP] = COMBO_ACTION(lrp)

};

/* COMBO_ACTION(x) is same as COMBO(x, KC_NO) */

void process_combo_event(uint16_t combo_index, bool pressed) {
  switch(combo_index) {
    case JK_ESC:
      if (pressed) {
        SEND_STRING(SS_TAP(X_ESC));
      }
      break;
    case QUOT:
      if (pressed) {
        SEND_STRING("'");
      }
      break;
    case DQUOT:
      if (pressed) {
        SEND_STRING("\"");
      }
      break;
    case LRB:
      if (pressed) {
        SEND_STRING("{}" SS_TAP(X_LEFT));
      }
      break;
    case LRS:
      if (pressed) {
        SEND_STRING("[]" SS_TAP(X_LEFT));
      }
      break;
    case LRP:
      if (pressed) {
        SEND_STRING("()" SS_TAP(X_LEFT));
      }
      break;
  }
}

